In [2]:
import torch
import numpy as np

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [4]:
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [6]:
torch.ones_like(x_data)

tensor([[1, 1],
        [1, 1]])

In [7]:
x_data = torch.rand_like(x_data, dtype=torch.float)
print(f"ones tensor: \n {x_data}\n")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random tensor : \n {x_rand} \n")

ones tensor: 
 tensor([[0.9917, 0.9453],
        [0.1603, 0.2815]])

Random tensor : 
 tensor([[0.1837, 0.9258],
        [0.0955, 0.8862]]) 



In [11]:
shape = (2,3)
ones_tensor = torch.ones(shape)

In [20]:
zeros_tensor = torch.zeros(shape)

In [13]:
print(f"Random Tensor:\n {ones_tensor} \n")

Random Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 



In [14]:
rand = torch.rand(3,4)

In [16]:
print(f"shape of tensor : {rand.shape}")
print(f"shape of tensor : {rand.dtype}")
print(f"shape of tensor : {rand.device}")

shape of tensor : torch.Size([3, 4])
shape of tensor : torch.float32
shape of tensor : cpu


In [18]:
if torch.cuda.is_available():
    tensor = ones_tensor.to('cuda')


In [19]:
tensor 

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [22]:
cat_tensor = torch.cat((zeros_tensor, ones_tensor))

In [23]:
cat_tensor 

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [24]:
mat1 = torch.rand(2,3)
mat2 = torch.rand(3,4)

In [26]:
mat1.matmul(mat2)

tensor([[0.1836, 0.4609, 0.3270, 0.5336],
        [0.2902, 1.0217, 0.2286, 0.5947]])

In [29]:
mat1.add_(5)

tensor([[5.0949, 5.3402, 5.3356],
        [5.7316, 5.4829, 5.0453]])

In [30]:
mat1.numpy()

array([[5.0948544, 5.340209 , 5.335579 ],
       [5.731629 , 5.482936 , 5.0453014]], dtype=float32)